#!/bin/bash
set -e

IMAGE_NAME="mythicsurf"
CONTAINER_NAME="mythicsurf"
MOUNT_DIR="/VOLUME"

# Build container image
docker build --tag "${IMAGE_NAME}" -f chromium.dockerfile .

# Delete previous instance if it exists
echo "STOPPING INSTANCE"
docker rm -f "${CONTAINER_NAME}" 2>/dev/null || true

# Create instance
echo "CREATING INSTANCE"
docker run -it -v "$(pwd):${MOUNT_DIR}" --name "${CONTAINER_NAME}" -h "${CONTAINER_NAME}" -d "${IMAGE_NAME}"

# Access instance
echo "ACCESSING INSTANCE"
docker exec -it "${CONTAINER_NAME}" /bin/bash
