#!/usr/bin/python3
import os
import sys
import shutil
import json
import re
from urllib.parse import urlparse
from contextlib import contextmanager

from build_vars import *

def new_section(msg):
    print("\n*******************************************************")
    print("* %s" % msg)
    print("*******************************************************\n")

def exit_if_fail_os_system(command):
    ret = os.system(command)
    if (ret):
        print("command failed with code %d: %s" % (ret, command))
        exit(1)

def exit_if_fail_os_makedirs(path, exist_ok=False):
    try:
        os.makedirs(path, exist_ok=exist_ok)
    except Exception as e:
        print("mkdir failed: %s: %s" % (path, e))
        exit(1)

@contextmanager
def exit_if_exception():
  try:
    yield
  except Exception as e:
    print("Something failed: %s" % e)
    exit(1)

#####################################################################
# Get the source and unpack it.
#####################################################################
new_section("Downloading and unpacking source:\n%s" % SOURCE_URL)

exit_if_fail_os_system("wget -N -nv %s" % SOURCE_URL)
exit_if_fail_os_system("tar -xf %s.tar.xz" % SOURCE_TARNAME)

#####################################################################
# Copy in default preferences and bookmarks
#####################################################################
new_section("Copying in preferences and bookmarks")

exit_if_fail_os_makedirs("%s/etc/mythicsurf" % STAGING_DIR)

codename = os.environ["MYTHIC_CODENAME"]
exit_if_fail_os_system("sed s/@CODENAME@/%s/ data/master_preferences > %s/etc/mythicsurf/master_preferences" % (codename, STAGING_DIR))

exit_if_fail_os_makedirs("%s/usr/share/mythicsurf" % STAGING_DIR)
exit_if_fail_os_system("cp data/initial_bookmarks.html %s/usr/share/mythicsurf" % STAGING_DIR)

exit_if_fail_os_makedirs("%s/usr/share/applications" % STAGING_DIR)
exit_if_fail_os_system("cp data/mythicsurf-browser.desktop %s/usr/share/applications" % STAGING_DIR)

#####################################################################
# Install MythicSurf icons (custom icons from data/icons/)
#####################################################################
new_section("Installing MythicSurf icons")

icons_src = os.path.join(curdir, "data", "icons", "hicolor")

with exit_if_exception():
    for root, dirs, files in os.walk(icons_src):
        for f in files:
            if f.endswith(".png") or f.endswith(".svg"):
                rel = os.path.relpath(root, icons_src)
                dest = os.path.join(STAGING_DIR, "usr/share/icons/hicolor", rel, "apps")
                exit_if_fail_os_makedirs(dest, exist_ok=True)
                src_file = os.path.join(root, f)
                ext = f.split(".")[-1]
                dest_file = os.path.join(dest, "mythicsurf." + ext)
                exit_if_fail_os_system("cp %s %s" % (src_file, dest_file))

#####################################################################
# Apply ubuntu patches
#####################################################################
new_section("Applying quilt patches")

series_file = "series.%s" % IMAGE_CODENAME
if IMAGE_32BIT:
    series_file += ".i386"

os.chdir(CHROME_SOURCE_DIR)
exit_if_fail_os_system("QUILT_SERIES=%s QUILT_PATCHES=%s quilt push -a --refresh" %
                       (os.path.join(curdir, "patches", series_file),
                        os.path.join(curdir, "patches")))

#####################################################################
# Search modifications
#####################################################################
new_section("Modifying search engines")

exit_if_fail_os_system("cp %s/data/prepopulated_engines.json third_party/search_engines_data/resources/definitions" % curdir)
exit_if_fail_os_system("cp %s/data/regional_settings.json third_party/search_engines_data/resources/definitions" % curdir)

new_section("Prep finished, run build")
